### ISSUE TITLE
sass中的em无法运算结果

### ISSUE THREAD

**Issue by wwhyes** [kevyu/weui-sass#13]
``` css
.weui_search_input {
    padding: 4px 0;
    width: 100%;
    height: 20/14em;
    border: 0;
    font-size: 14px;
    line-height: 20/14em;
    box-sizing: content-box;
    background: transparent;
    &:focus {
        outline: none;
    }
}
```

这个在我这边无法得到相应结果~然后我改成了:

``` css
.weui_search_input {
    padding: 4px 0;
    width: 100%;
    height: 20/14*1em;
    border: 0;
    font-size: 14px; 
    line-height: 20/14*1em;
    box-sizing: content-box;
    background: transparent;
    &:focus {
        outline: none;
    }
}
```

然后我相对应搜了下这个问题
https://github.com/sass/sass/issues/489
